name: deploy-docC-on-github-page

on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-demo-app:
    uses: leboncoin/spark-ios-common/.github/workflows/deployDocCPage.yml@main
